buildscript {
    repositories {
       maven { url uri('https://maven.openflexo.org/artifactory/openflexo-deps/') }
    }
    dependencies {
		classpath group: 'org.openflexo', name: 'buildplugin', version: '0.3'
		classpath group: 'org.openflexo', name: 'buildconfig', version: '3.0'
        classpath 'org.openflexo:gradle-sablecc-plugin:[1.3.0,)'
	}
}

// TODO fix with a better way
configurations {
    // For compiled/binary dependencies
    compileLibs
}

dependencies {
    // https://mvnrepository.com/artifact/org.alloytools/org.alloytools.alloy.dist
	compileLibs fileTree(dir: 'lib', include: '*.jar') // "org.alloytools:org.alloytools.alloy.dist:6.2.0"
}

version = "3.0"
apply plugin: 'org.openflexo.buildconfig'